# Generated by Django 2.2.16 on 2020-10-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_category_parenting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="parenting",
        ),
    ]
